[PHP]
; Configurações básicas
memory_limit = 512M
max_execution_time = 600
max_input_time = 600
upload_max_filesize = 100M
post_max_size = 100M
file_uploads = On
allow_url_fopen = On
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/log/php/php_errors.log
default_charset = "UTF-8"
date.timezone = UTC

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=1