[www]
user = laravel
group = laravel

listen = 9000

pm = static
pm.max_children = 8
pm.max_requests = 1000

request_terminate_timeout = 60s

clear_env = no

catch_workers_output = yes
decorate_workers_output = no
